-- =============================================================================
-- Stage 0.2 — Infrastructure: Storage buckets (avatars, covers)
-- =============================================================================
-- Creates the two Supabase Storage buckets referenced in §5.3 (personal
-- cabinet / profile editing) for profile avatars and cover images.
--
-- Both buckets are PRIVATE (public = false): per §2.3 the spec mandates
-- Storage access via **signed URLs**, not public bucket reads. Signed URLs
-- are minted server-side (Server Actions / Route Handlers using the
-- anon/session client, which is allowed to sign URLs for objects the caller
-- can already resolve the path to) and therefore intentionally bypass the
-- SELECT policies below — so we do NOT add a broad `for select using (true)`
-- policy on these buckets. Only owners (and, implicitly, server-side signed
-- URL issuance) can access the underlying objects.
--
-- Object path convention enforced by RLS: `{bucket}/{auth.uid()}/{filename}`
-- i.e. the first path segment (`storage.foldername(name))[1]`) must equal the
-- authenticated user's uid. This keeps every user's uploads namespaced to
-- their own folder and lets a single simple policy cover inserts/updates/
-- deletes for both buckets.
--
-- Idempotent: safe to re-run and safe to apply via `supabase db push` on
-- hosted Supabase. Do not edit this file after it has been applied —
-- add a new migration instead.
-- =============================================================================

-- -----------------------------------------------------------------------------
-- Buckets
-- -----------------------------------------------------------------------------

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'avatars',
  'avatars',
  false,
  5242880, -- 5 MB
  array['image/png', 'image/jpeg', 'image/webp', 'image/avif']
)
on conflict (id) do nothing;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'covers',
  'covers',
  false,
  10485760, -- 10 MB
  array['image/png', 'image/jpeg', 'image/webp', 'image/avif']
)
on conflict (id) do nothing;

-- -----------------------------------------------------------------------------
-- RLS policies on storage.objects, scoped per bucket via bucket_id + owner
-- folder convention: objects must live under `{auth.uid()}/...` within the
-- bucket. storage.objects already has RLS enabled by default on Supabase.
-- -----------------------------------------------------------------------------

-- avatars: insert into own folder
drop policy if exists "avatars_insert_own_folder" on storage.objects;
create policy "avatars_insert_own_folder"
  on storage.objects for insert to authenticated
  with check (
    bucket_id = 'avatars'
    and (storage.foldername(name))[1] = (select auth.uid())::text
  );

-- avatars: update own objects
drop policy if exists "avatars_update_own" on storage.objects;
create policy "avatars_update_own"
  on storage.objects for update to authenticated
  using (
    bucket_id = 'avatars'
    and (storage.foldername(name))[1] = (select auth.uid())::text
  )
  with check (
    bucket_id = 'avatars'
    and (storage.foldername(name))[1] = (select auth.uid())::text
  );

-- avatars: delete own objects
drop policy if exists "avatars_delete_own" on storage.objects;
create policy "avatars_delete_own"
  on storage.objects for delete to authenticated
  using (
    bucket_id = 'avatars'
    and (storage.foldername(name))[1] = (select auth.uid())::text
  );

-- covers: insert into own folder
drop policy if exists "covers_insert_own_folder" on storage.objects;
create policy "covers_insert_own_folder"
  on storage.objects for insert to authenticated
  with check (
    bucket_id = 'covers'
    and (storage.foldername(name))[1] = (select auth.uid())::text
  );

-- covers: update own objects
drop policy if exists "covers_update_own" on storage.objects;
create policy "covers_update_own"
  on storage.objects for update to authenticated
  using (
    bucket_id = 'covers'
    and (storage.foldername(name))[1] = (select auth.uid())::text
  )
  with check (
    bucket_id = 'covers'
    and (storage.foldername(name))[1] = (select auth.uid())::text
  );

-- covers: delete own objects
drop policy if exists "covers_delete_own" on storage.objects;
create policy "covers_delete_own"
  on storage.objects for delete to authenticated
  using (
    bucket_id = 'covers'
    and (storage.foldername(name))[1] = (select auth.uid())::text
  );
