-- =============================================================================
-- Brand assets: public Storage bucket for transactional-email images
-- =============================================================================
-- Transactional emails (Resend, via `lib/email/` and the `process-email-queue`
-- Edge Function) need an absolute, publicly reachable HTTPS URL for the logo
-- shown in the email header. Localhost is unreachable from a mail client, and
-- production is not deployed yet, so a public Storage bucket is used instead
-- of a same-origin `/public` asset: the URL is stable regardless of Vercel
-- deploys and works today.
--
-- Unlike `avatars` / `covers` / `reel-life` / `promo-video` (owner-scoped,
-- `{auth.uid()}/...` folder convention, writable by the authenticated owner),
-- this bucket has NO client write policies at all — brand assets are not
-- user content, so only the service role (which bypasses RLS entirely) may
-- write here, matching the project-wide "money tables and platform-owned
-- data are service-role-only" pattern. Only a public SELECT policy is added.
--
-- Idempotent: safe to re-run and safe to apply via `supabase db push` on
-- hosted Supabase. Do not edit this file after it has been applied — add a
-- new migration instead.
-- =============================================================================

-- -----------------------------------------------------------------------------
-- Bucket
-- -----------------------------------------------------------------------------
-- Small size limit and image-only MIME allow-list: this bucket is for a
-- handful of platform-owned brand assets (logo, wordmark, favicon variants
-- used in emails), not general uploads. 2 MB comfortably covers a retina PNG
-- logo (~30-60 KB) with headroom, while still ruling out accidental misuse
-- as a general file host.
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'brand-assets',
  'brand-assets',
  true,
  2097152, -- 2 MB
  array['image/png', 'image/jpeg', 'image/webp', 'image/svg+xml']
)
on conflict (id) do nothing;

-- -----------------------------------------------------------------------------
-- RLS policy on storage.objects — public read only, no client write policy
-- -----------------------------------------------------------------------------
-- No `to` clause -> applies to every role including anon: an email client /
-- Gmail image proxy fetches this URL with no Supabase session at all.
drop policy if exists "brand_assets_public_read" on storage.objects;
create policy "brand_assets_public_read"
  on storage.objects for select
  using (bucket_id = 'brand-assets');

-- Deliberately no insert/update/delete policy for this bucket: only the
-- service role (which bypasses RLS) may write brand assets. This mirrors the
-- project rule that platform-owned data gets no client write policies (see
-- CLAUDE.md "Money is server-only" and the `transactions`/`payouts` pattern),
-- extended here to brand assets since they are likewise never user-supplied.
